server:
  port: 8000

spring:
  profiles:
    active: local
    
  #컨트롤러가 뷰 이름을 반환할때 thymeleaf/ 로 시작하면 타임리프로 처리하도록 view-names 지정  thymeleaf:    view-names: thymeleaf/*
    prefix: classpath:/templates/
    suffix: .html
    #thymeleaf를 사용하다 수정 사항이 생길 때 수정을 하면 재시작을 해줘야 한다. 이를 무시하고 브라우저 새로고침시 수정사항 반영을 취해 cache=false 설정(추후 프로필로 변경하자)
    cache: false
    check-template-location: true
              
mybatis:
  # mybatis 매핑 type을 짧게 쓰기 위한 설정 
  # mapper.xml에서 resultType을 지정할 때 com.god.bo.test.vo.TestVo 대신 TestVo로 간략히 할 수 있다.  type-aliases-package: sinsuper.demo.springboot.vo
  # mapper.xml 위치 지정 
  # **은 하위 폴더 레벨에 상관없이 모든 경로를 뜻하며, *는 아무 이름이나 와도 된다는것을 뜻합니다.
  mapper-locations:  - mybatis/**/*.xml

logging:  level:    root: debug
    
---
spring:  config:    activate:      on-profile: local
  devtools:
    livereload:
      enabled: true      datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/sakila?characterEncoding=UTF-8&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/sakila?characterEncoding=UTF-8&serverTimezone=UTC
    username: spring
    password: spring  #비밀 번호 보안 확인
    hikari:      connection-test-query: SELECT 1

---
spring:
  config:
    activate:
      on-profile: dev
  devtools:
    livereload:
      enabled: true        
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/sakila?characterEncoding=UTF-8&serverTimezone=UTC
    hikari:
      username: spring
      password: spring  #비밀 번호 보안 확인      
    
---
spring:
  config:
    activate:
      on-profile: prod
  devtools:
    livereload:
      enabled: false        
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy 
    url: jdbc:log4jdbc:mysql://localhost:3306/sakila?characterEncoding=UTF-8&serverTimezone=UTC
    username: spring
    password: spring  #비밀 번호 보안 확인      
    